- hosts: webserver
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes

  vars:
    apache_package_name: apache2
    mysql_package_name: php-mysql
    php_package_name: libapache2-mod-php
    service_name: apache2
    document_root: /var/www/html
    http_host: harsha.com
    http_conf: harsha.com.conf
    http_port: 80
    mysql_root_password: harshamysql
    mysql_db: wpdb
    mysql_user: wpuser
    mysql_password: harsha123

  tasks:
    - name: Apache, PHP and MySQL must be installed
      apt:
        update_cache: yes
        name: "{{item}}"
        state: latest
      loop: ['apache2','php-mysql','libapache2-mod-php','python3-pymysql','mysql-server']

    - name: Create the website root directory
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data" 

    - name: Setting the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        update_password: always
        check_implicit_admin: true
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create wordpress database
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user 
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"


  # WordPress Configuration
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"
      tags: [ wordpress ]       
    
    - name: Set up Apache VirtualHost
      template:
        src: "apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Restart Apache

    - name: Download wordpress 
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"
 
    - name: Set ownership
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Set Directory permissons
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 2775 {} \\;"

    - name: Set File permissons
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 0664 {} \\;"
   
    - name: Makesure Apache is started
      service:
        enabled: yes
        name: "{{service_name}}"
        state: started

    - name: Set up wp-config
      template:
        src: "wp-config.php.j2"
        dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: "{{service_name}}"
        state: restarted
             
